disabled_rules: # rule identifiers to exclude from running
  - opening_brace
#   - closure_parameter_position
#   - type_name
#   - todo
#   - trailing_whitespace
#   - cyclomatic_complexity
#  - discarded_notification_center_observer # broken. Warns if we store in array
#  - identifier_name # warns about unicode symbols

# variable_name:
#   excluded: # excluded via string array
#     - id

# type_body_length:
#   warning: 300
#   error: 400

# file_length:
#   warning: 600
#   error: 1200

# nesting:
#   type_level:
#     warning: 2
#   statement_level:
#     warning: 10
